Edit front end
Cellular-Imaging-Amsterdam-UMC/NL-BIOMERO pull request #3
Opened 2024-01-18 14:30 UTC by rodrigolearns

Re-introduced front-end changes for new omero-server and omero-web versions.
View the UpgradeFrontEnd.md file for a detailed overview.
Summary:
>Non-hosted logo in login page
>No server selector in login page
>Double-Click for better file browsing
>Improved top menu button clarity

2024-01-18 16:22 UTC, TorecLuik requested changes
Check the comments in the UpgradeFrontEnd.md, I think we need to clean this up before we publish it. 

I provided one possible way of doing it, please try it out.

There are also even neater alternatives, which are not out of the scope either, like cloning the web repository to an CellularImaging one and adding a commit with the changed files there. Then you could pull that github inside the Dockerfile for the same effect.

But 818 files for review is infeasible. **DENIED** =D

2024-01-18 16:22 UTC, TorecLuik commented on UpgradeFrontEnd.md
> +**local_omeroweb\webclient\static\webclient\image\Amsterdam-UMC.png**
It is very unlikeable to hardcode an AUMC logo if we want to share this. 
Please make it configurable, e.g. by at least renaming it to something generic. Preferably the location of the logo is also outside of the local_omeroweb folder so that it is clear that we added it. Perhaps in the web folder and then added via the Dockerfile to the right location inside the container.

2024-01-18 16:22 UTC, TorecLuik commented on UpgradeFrontEnd.md
> +Removed Mapr tab as it is not commonly used and instead clutters the middle header. History button title changed to Upload History.
Did you also uninstall Mapr? As in, are we still installing it in the Dockerfile? That would be a waste of resources. Cut it out at all spots, not just in the configuration. Feel free to exclude other plugins as well by the way.

2024-01-18 16:22 UTC, TorecLuik commented on UpgradeFrontEnd.md
> +**local_omeroweb\webgateway\static\webgateway\css\ome.header.css**
To be clear, these changes shown here are the only actual changes you made? 
I would really like there to be a clearer separation between your changed files and the ' copies from OME ' files. 
Because we need to track changes made to these files, and there are too many files (818 files in review). We don't know which files you changed 1 line and which files are unchanged. You paste it here, which is good for now, but not feasible as a publishable solution. 

Now that you did most of the frontend, we can neaten it up a bit.
I think there is a middle road to be found here between ' neat '  and ' still works in practice ':
1. First, take all the files you changed (and only those files) and add them externally in the web folder. 
2. Then paste them back on the right location from within the Dockerfile. Now we are explicit which files we changed, as we can see it in the Dockerfile and in the web subfolder. (Just a ADD blabla /correct/location/for/blabla)
3. I think you can remove the whole remaining local_web folder then, because in theory those remaining files are now all literal copies of where you normally mount the local_web folder (in the Dockerfile). This will make development more of a bitch, but this is a finished commit and you weren't using the ' folder inside web and Dockerfile ' for development anyway; you were mounting in the docker-compose.

2024-01-18 16:23 UTC, TorecLuik commented on web/local_omeroweb/.gitignore
Note, you probably wont need this if we do the other changes as there won't be a local_omero

2024-01-31 14:45 UTC, CellularImagingCF requested changes
Nicely minimized. Let's tackle the final 2 steps and then merge and deploy it. 

1. No NKI image. If you want to rotate, rotate something about the AMC / Core Facility
2. Try to use this OMERO template directory instead of editing the Python library directly

2024-01-31 14:45 UTC, CellularImagingCF commented on web/local_omeroweb_edits/Display_Images/NKI.png
I don't want to display NKI at AMC.

2024-01-31 14:45 UTC, CellularImagingCF commented on web/Dockerfile
> +WORKDIR /opt/omero/web/venv3/lib/python3.9/site-packages/omeroweb
Works for now, but nicer to use this config/ template directory instead of editing the python library directly.

2024-02-06 16:56 UTC, CellularImagingCF approved these changes

2024-02-06 16:57 UTC, TorecLuik approved these changes

2024-02-06 16:58 UTC, merged